In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import math
import random

In [2]:
#load data #0,  1,  2,  3,
city_name=['A','B','C','D']
city_weight=[30,30,35,25,40]
city_weight=np.array(city_weight)

city_count = len(city_name)
Distance=np.zeros([city_count,city_count])

# for i in range(city_count):
#     for j in range(city_count):

##A
Distance[0][1]=30
Distance[0][2]=50
Distance[0][3]=40
##B
Distance[1][0]=30
Distance[1][2]=30
Distance[1][3]=35
##C
Distance[2][0]=50
Distance[2][1]=30
Distance[2][3]=25
##D
Distance[3][0]=40
Distance[3][1]=35
Distance[3][2]=25


print(Distance)

[[ 0. 30. 50. 40.]
 [30.  0. 30. 35.]
 [50. 30.  0. 25.]
 [40. 35. 25.  0.]]


In [3]:
# Population
count = 300
improve_numb = 10000
iteration = 400

retain_rate = 0.3
random_select_rate = 0.5
mutation_rate = 0.1

origin = 2
index = [i for i in range(city_count)]
index.remove(2)

In [4]:
# total distance
def get_total_distance(x):
    distance = 0
    distance += Distance[origin][x[0]]
    for i in range(len(x)):
        if i == len(x) - 1:
            distance += Distance[origin][x[i]]
        else:
            distance += Distance[x[i]][x[i + 1]]
    return distance

In [5]:
def effort(x):
    i = 0
    distance = get_total_distance(x)
    while i < improve_numb:
        # randint [a,b]
        u = random.randint(0, len(x) - 1)
        v = random.randint(0, len(x) - 1)
        if u != v:
            new_x = x.copy()
            t = new_x[u]
            new_x[u] = new_x[v]
            new_x[v] = t
            new_distance = get_total_distance(new_x)
            if new_distance < distance:
                distance = new_distance
                x = new_x.copy()
        else:
            continue
        i += 1

In [6]:
def selection(population):
    graded = [[get_total_distance(x), x] for x in population]
    graded = [x[1] for x in sorted(graded)]
    retain_length = int(len(graded) * retain_rate)
    parents = graded[:retain_length]
    for chromosome in graded[retain_length:]:
        if random.random() < random_select_rate:
            parents.append(chromosome)
    return parents

In [7]:
def crossover(parents):
    target_count = count - len(parents)
    children = []
    while len(children) < target_count:
        male_index = random.randint(0, len(parents) - 1)
        female_index = random.randint(0, len(parents) - 1)
        if male_index != female_index:
            male = parents[male_index]
            female = parents[female_index]

            left = random.randint(0, len(male) - 2)
            right = random.randint(left + 1, len(male) - 1)

            # Cross section
            gene1 = male[left:right]
            gene2 = female[left:right]

            child1_c = male[right:] + male[:right]
            child2_c = female[right:] + female[:right]
            child1 = child1_c.copy()
            child2 = child2_c.copy()

            for o in gene2:
                child1_c.remove(o)

            for o in gene1:
                child2_c.remove(o)

            child1[left:right] = gene2
            child2[left:right] = gene1

            child1[right:] = child1_c[0:len(child1) - right]
            child1[:left] = child1_c[len(child1) - right:]

            child2[right:] = child2_c[0:len(child1) - right]
            child2[:left] = child2_c[len(child1) - right:]

            children.append(child1)
            children.append(child2)

    return children


In [8]:
# Mutation
def mutation(children):
    for i in range(len(children)):
        if random.random() < mutation_rate:
            child = children[i]
            u = random.randint(1, len(child))
            child = children[i]
            child = child[0:u]  



In [9]:
# Get output
def get_result(population):
    graded = [[get_total_distance(x), x] for x in population]
    graded = sorted(graded)
    return graded[0][0], graded[0][1]
    

In [10]:
population = []
for i in range(count):
    x = index.copy()
    random.shuffle(x)
    effort(x)
    population.append(x)

register = []
i = 0
distance, result_path = get_result(population)
while i < iteration:
    parents = selection(population)
    # Cross over
    children = crossover(parents)
    # Mutation
    mutation(children)
    # Update the population
    population = parents + children

    distance, result_path = get_result(population)
    register.append(distance)
    i = i + 1

result_path = [origin] + result_path + [origin]
print(distance)
print(result_path)





125.0
[2, 1, 0, 3, 2]
